DROP TABLE IF EXISTS USERS;
DROP TABLE IF EXISTS SESSIONS;
DROP TABLE IF EXISTS POSTS;
DROP TABLE IF EXISTS COMMENTS;
DROP TABLE IF EXISTS TAGS;
DROP TABLE IF EXISTS LIKE_POSTS;
DROP TABLE IF EXISTS LIKE_COMMENTS;