CREATE extension citext;
CREATE DOMAIN EMAIL AS citext CHECK (VALUE ~* '^[A-Za-z0-9._%-]+@[A-Za-z0-9.-]+[.][A-Za-z]+$');

CREATE TABLE IF NOT EXISTS USERROLES (
    ROLE TEXT NOT NULL UNIQUE
);
INSERT INTO USERROLES (ROLE) VALUES ('user'), ('mod'), ('admin');

CREATE TABLE IF NOT EXISTS USERLEVELS (
    LEVEL TEXT NOT NULL UNIQUE
);
INSERT INTO USERLEVELS (LEVEL) VALUES ('wood'), ('stone'), ('copper'), ('bronze'), ('iron'), ('steel'), ('silver'), ('gold'), ('mithril');

CREATE TABLE IF NOT EXISTS USERFLAIRS (
    FLAIR TEXT NOT NULL UNIQUE
);
INSERT INTO USERFLAIRS (FLAIR) VALUES ('none'), ('verified'), ('distinguished'), ('eminent');

CREATE TABLE IF NOT EXISTS USERS (
    UNQID TEXT NOT NULL UNIQUE,
    NICK TEXT DEFAULT 'Nony Mouse',
    THUMB TEXT,
    FLAIR Text REFERENCES USERFLAIRS(FLAIR) DEFAULT 'none',
    ROLE Text REFERENCES USERROLES(ROLE) DEFAULT 'user',
    LEVEL Text REFERENCES USERLEVELS(LEVEL) DEFAULT 'wood',
    STARS INT DEFAULT 1,
    IS_DELETED BOOL DEFAULT FALSE,
    EMAIL EMAIL NOT NULL UNIQUE,
    PASSWORD TEXT NOT NULL,
    WARNED_TILL TIMESTAMP,
    BANNED_TILL TIMESTAMP,
    WARNED_COUNT INT DEFAULT 0,
    BANNED_COUNT INT DEFAULT 0,
    WARNED_AT TIMESTAMP,
    BANNED_AT TIMESTAMP,
    VERIFIED_AT TIMESTAMP,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    DELETED_AT TIMESTAMP
);
ALTER TABLE USERS ADD CONSTRAINT USERS_NICK_LENGTH CHECK (length(NICK) BETWEEN 3 and 64);
ALTER TABLE USERS ADD CONSTRAINT USERS_THUMB_LENGTH CHECK (length(THUMB) BETWEEN 12 and 128);
ALTER TABLE USERS ADD CONSTRAINT USERS_EMAIL_LENGTH CHECK (length(EMAIL) BETWEEN 8 and 64);
ALTER TABLE USERS ADD CONSTRAINT USERS_PASSWORD_LENGTH CHECK (length(PASSWORD) BETWEEN 8 and 64);

CREATE TABLE IF NOT EXISTS SESSIONS (
    UNQID TEXT NOT NULL UNIQUE,
    USER_ID TEXT NOT NULL REFERENCES USERS(UNQID),
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    LAST_USED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    EXPIRES_AT TIMESTAMP
);
ALTER TABLE SESSIONS ADD CONSTRAINT SESSIONS_ID_LENGTH CHECK (length(UNQID) BETWEEN 128 and 256);

----------------------------------------------
CREATE TABLE IF NOT EXISTS AUTH_BASIC (
    USER_ID_REF TEXT NOT NULL UNIQUE REFERENCES USERS(UNQID),
    USER_EMAIL EMAIL NOT NULL UNIQUE,
    USER_PASSWORD TEXT NOT NULL,
    VERIFIED_AT TIMESTAMP
);
ALTER TABLE AUTH_BASIC ADD CONSTRAINT USERS_EMAIL_LENGTH CHECK (length(USER_EMAIL) BETWEEN 8 and 64);
ALTER TABLE AUTH_BASIC ADD CONSTRAINT USERS_PASSWORD_LENGTH CHECK (length(USER_PASSWORD) BETWEEN 8 and 64);

-- CREATE TABLE IF NOT EXISTS AUTH_GOOGLE (
--     USER_GOOGLE_ID TEXT NOT NULL UNIQUE,
--     REFRESH_TOKEN TEXT NOT NULL,
--     REFRESHED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
-- );

-- CREATE TABLE IF NOT EXISTS AUTH_FACEBOOK (
--     USER_FACEBOOK_ID TEXT NOT NULL UNIQUE,
-- );
-- CREATE TABLE IF NOT EXISTS AUTH_GITHUB (
--     USER_GITHUB_ID TEXT NOT NULL UNIQUE,
-- );



CREATE TYPE POSTCATEGORIES AS ENUM ('offbeat','meta', 'science&nature', 'world&business' 'lifestyle', 'entertainment', 'sports');

CREATE TABLE IF NOT EXISTS POSTS (
    UNQID TEXT NOT NULL UNIQUE,
    TITLE TEXT CONSTRAINT TITLE_VALIDATE CHECK (CHAR_LENGTH(TITLE) <= 255),
    LINK TEXT,
    THUMB TEXT,
    CONTENT TEXT,
    LIKES INT DEFAULT 1,
    TAGS JSONB,
    USER_ID TEXT REFERENCES USERS(UNQID),
    USER_NICK TEXT,
    USER_FLAIR TEXT,
    IS_DELETED BOOL DEFAULT FALSE,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    DELETED_AT TIMESTAMP
);

CREATE TABLE IF NOT EXISTS ALLOWED_TAGS (
    UNQID TEXT NOT NULL UNIQUE,
    NAME TEXT NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    DELETED_AT TIMESTAMP
);

CREATE TABLE IF NOT EXISTS COMMENTS(
    UNQID TEXT PRIMARY KEY,
    POST_ID TEXT,
    PARENT_ID TEXT,
    CONTENT TEXT,
    LIKES INT DEFAULT 1,
    USER_ID TEXT NOT NULL,
    USER_NICK TEXT,
    USER_FLAIR TEXT,
    IS_DELETED BOOL DEFAULT FALSE,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    DELETED_AT TIMESTAMP
);

CREATE TYPE VOTETYPE AS ENUM ('up','none','down');

CREATE TABLE IF NOT EXISTS TAGS (
    NAME TEXT NOT NULL,
    POST_ID TEXT NOT NULL,
    USER_ID TEXT NOT NULL,
    VOTED VOTETYPE NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    DELETED_AT TIMESTAMP
);


CREATE TABLE IF NOT EXISTS LIKE_POSTS (
    POST_ID TEXT NOT NULL,
    USER_ID TEXT NOT NULL,
    VOTED BOOL NOT NULL DEFAULT TRUE,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    DELETED_AT TIMESTAMP,
    CONSTRAINT "unique_user_and_post_combo" PRIMARY KEY (POST_ID, USER_ID)
);

CREATE TABLE IF NOT EXISTS LIKE_COMMENTS (
    POST_ID TEXT NOT NULL,
    COMMENT_ID TEXT NOT NULL,
    USER_ID TEXT NOT NULL,
    VOTED BOOL NOT NULL DEFAULT TRUE,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    DELETED_AT TIMESTAMP,
    CONSTRAINT "unique_user_and_comment_combo" PRIMARY KEY (COMMENT_ID, USER_ID)
);

CREATE TABLE IF NOT EXISTS REPORT_POSTS (
    POST_ID TEXT NOT NULL,
    USER_ID TEXT NOT NULL,
    REASON TEXT NOT NULL,
    DETAILS TEXT NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    DELETED_AT TIMESTAMP,
    CONSTRAINT "unique_user_and_post_combo_for_reports" PRIMARY KEY (POST_ID, USER_ID)
);

CREATE TABLE IF NOT EXISTS REPORT_COMMENTS (
    COMMENT_ID TEXT NOT NULL,
    USER_ID TEXT NOT NULL,
    REASON TEXT NOT NULL,
    DETAILS TEXT NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    DELETED_AT TIMESTAMP,
    CONSTRAINT "unique_user_and_comment_combo_for_reports" PRIMARY KEY (COMMENT_ID, USER_ID)
);

-- CREATE TABLE IF NOT EXISTS FLAG_POSTS (
--     POST_ID TEXT NOT NULL,
--     COMMENT_ID TEXT NOT NULL,
--     USER_ID TEXT NOT NULL,
--     CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
--     UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
--     DELETED_AT TIMESTAMP
-- );
-- CREATE TABLE IF NOT EXISTS FLAG_COMMENTS (
--     POST_ID TEXT NOT NULL,
--     COMMENT_ID TEXT NOT NULL,
--     USER_ID TEXT NOT NULL,
--     CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
--     UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
--     DELETED_AT TIMESTAMP
-- );

-- CREATE TABLE IF NOT EXISTS POSTS (
--     UNQID TEXT NOT NULL UNIQUE,
--     TITLE TEXT NOT NULL,
--     LINK TEXT,
--     THUMB TEXT,
--     CONTENT TEXT,
--     LIKED_COUNT INT DEFAULT 1,
--     TAGS JSONB,
--     COMMENTS JSONB,
--     USER_ID TEXT NOT NULL,
--     USER_NICK TEXT,
--     USER_FLAIR TEXT DEFAULT 'Silly Goose',
--     IS_DELETED BOOL DEFAULT FALSE,
--     CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
--     UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
--     DELETED_AT TIMESTAMP
-- );